# Generated by Django 5.1.1 on 2024-09-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag_articles_alter_scope_article_alter_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
