# Generated by Django 5.1.1 on 2024-09-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='ArticleScope',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='articles.ArticleScope', to='articles.tag'),
        ),
    ]
